export const readerCopy = {
  "bag.books": "Kitaplar",
  "reader.menu": "Kitap",
  "reader.add": "Kitap ekle",
  "reader.file": "PDF veya EPUB dosyası",
  "reader.open": "Oku / Devam et",
  "reader.empty": "Henüz bir kitap açmadın. Listelerinden bir kitap seçip Oku düğmesine dokun.",
  "reader.browse": "Beğenilenler’e git",
  "reader.back": "Okumadan çık",
  "reader.loading": "Kitabın hazırlanıyor…",
  "reader.error": "Kitap açılamadı. Dosyayı ve cihazındaki boş alanı kontrol edip yeniden dene.",
  "reader.saveError": "Okuma konumun veya notların kaydedilemedi. Yeniden dene.",
  "reader.retry": "Yeniden dene",
  "reader.previous": "Önceki sayfa",
  "reader.next": "Sonraki sayfa",
  "reader.page": "Sayfa",
  "reader.zoom": "Yakınlaştırma",
  "reader.fontSize": "Yazı boyutu",
  "reader.lineHeight": "Satır aralığı",
  "reader.theme": "Okuma teması",
  "reader.dark": "Koyu",
  "reader.light": "Açık",
  "reader.contents": "İçindekiler",
  "reader.highlight": "Seçimi vurgula",
  "reader.note": "Notun (isteğe bağlı)",
  "reader.notes": "Vurgular ve notlar",
  "reader.selection": "Vurgulamak için metin seç.",
  "reader.download": "Kitap dosyasını indir",
  "reader.backupScope": "Yedeğe okuma konumu ve notlar dahil edilir. Kitap dosyalarını ayrıca indirip sakla.",
  "reader.attach": "Okumak için dosya ekle",
  "reader.required": "Yeni kitap için PDF veya EPUB dosyası seç.",
  "reader.favorite": "Beğenilenler üyeliğini değiştir",
  "reader.vird": "Virdlerim üyeliğini değiştir",
} as const;
